Objective: Iwant to understand the content distribution of Netflix and what patterns exists in them.

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv(r"C:\Users\HP\Downloads\archive\titles.csv")
data

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts300399,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,51,['documentation'],['US'],1.0,NaN,NaN,NaN,0.601,NaN
1,tm82169,Rocky,MOVIE,"When world heavyweight boxing champion, Apollo...",1976,PG,119,"['drama', 'sport']",['US'],NaN,tt0075148,8.1,588100.0,106.361,7.782
2,tm17823,Grease,MOVIE,Australian good girl Sandy and greaser Danny f...,1978,PG,110,"['romance', 'comedy']",['US'],NaN,tt0077631,7.2,283316.0,33.160,7.406
3,tm191099,The Sting,MOVIE,A novice con man teams up with an acknowledged...,1973,PG,129,"['crime', 'drama', 'comedy', 'music']",['US'],NaN,tt0070735,8.3,266738.0,24.616,8.020
4,tm69975,Rocky II,MOVIE,After Rocky goes the distance with champ Apoll...,1979,PG,119,"['drama', 'sport']",['US'],NaN,tt0079817,7.3,216307.0,75.699,7.246
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6132,tm1303784,عبود في البيت,MOVIE,Two young boys must work together to stop robb...,2023,NaN,81,"['family', 'comedy']",['KW'],NaN,NaN,NaN,NaN,3.351,2.000
6133,tm1260999,Sweetie,MOVIE,"‘Theatre is my life,’ Yıldız Kenter admits in ...",2023,NaN,120,['documentation'],['TR'],NaN,tt26349328,7.9,209.0,2.450,7.200
6134,tm1310286,Sommore: Queen Chandelier,MOVIE,This Queen of Comedy shines as she takes the s...,2023,NaN,69,['comedy'],['US'],NaN,tt21033382,6.1,91.0,1.960,NaN
6135,tm1072700,All Na Vibes,MOVIE,The lives of three teenagers and a hit-man int...,2023,NaN,80,['drama'],['NG'],NaN,tt14922926,5.2,18.0,1.357,4.000
6136,tm561709,Going to Heaven,MOVIE,"A story about young boy sultan, 11 years old l...",2023,NaN,90,['family'],['AE'],NaN,tt4623222,7.0,40.0,NaN,NaN

Cleaning unnecessary columns from the data to enhance readability of important data.

In [3]:
data.drop_duplicates()

,id,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,ts300399,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,51,['documentation'],['US'],1.0,NaN,NaN,NaN,0.601,NaN
1,tm82169,Rocky,MOVIE,"When world heavyweight boxing champion, Apollo...",1976,PG,119,"['drama', 'sport']",['US'],NaN,tt0075148,8.1,588100.0,106.361,7.782
2,tm17823,Grease,MOVIE,Australian good girl Sandy and greaser Danny f...,1978,PG,110,"['romance', 'comedy']",['US'],NaN,tt0077631,7.2,283316.0,33.160,7.406
3,tm191099,The Sting,MOVIE,A novice con man teams up with an acknowledged...,1973,PG,129,"['crime', 'drama', 'comedy', 'music']",['US'],NaN,tt0070735,8.3,266738.0,24.616,8.020
4,tm69975,Rocky II,MOVIE,After Rocky goes the distance with champ Apoll...,1979,PG,119,"['drama', 'sport']",['US'],NaN,tt0079817,7.3,216307.0,75.699,7.246
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6132,tm1303784,عبود في البيت,MOVIE,Two young boys must work together to stop robb...,2023,NaN,81,"['family', 'comedy']",['KW'],NaN,NaN,NaN,NaN,3.351,2.000
6133,tm1260999,Sweetie,MOVIE,"‘Theatre is my life,’ Yıldız Kenter admits in ...",2023,NaN,120,['documentation'],['TR'],NaN,tt26349328,7.9,209.0,2.450,7.200
6134,tm1310286,Sommore: Queen Chandelier,MOVIE,This Queen of Comedy shines as she takes the s...,2023,NaN,69,['comedy'],['US'],NaN,tt21033382,6.1,91.0,1.960,NaN
6135,tm1072700,All Na Vibes,MOVIE,The lives of three teenagers and a hit-man int...,2023,NaN,80,['drama'],['NG'],NaN,tt14922926,5.2,18.0,1.357,4.000
6136,tm561709,Going to Heaven,MOVIE,"A story about young boy sultan, 11 years old l...",2023,NaN,90,['family'],['AE'],NaN,tt4623222,7.0,40.0,NaN,NaN

In [4]:
data=data.drop(columns=["id","imdb_id"])

Cleaning the columns tpo remove unneeded characters that might cause issues in future analysis

In [5]:
data["genres"]=data["genres"].str.replace("[","")
data["genres"]=data["genres"].str.replace("]","")
data["genres"]=data["genres"].str.replace("'","")

In [6]:
data

,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,51,documentation,['US'],1.0,NaN,NaN,0.601,NaN
1,Rocky,MOVIE,"When world heavyweight boxing champion, Apollo...",1976,PG,119,"drama, sport",['US'],NaN,8.1,588100.0,106.361,7.782
2,Grease,MOVIE,Australian good girl Sandy and greaser Danny f...,1978,PG,110,"romance, comedy",['US'],NaN,7.2,283316.0,33.160,7.406
3,The Sting,MOVIE,A novice con man teams up with an acknowledged...,1973,PG,129,"crime, drama, comedy, music",['US'],NaN,8.3,266738.0,24.616,8.020
4,Rocky II,MOVIE,After Rocky goes the distance with champ Apoll...,1979,PG,119,"drama, sport",['US'],NaN,7.3,216307.0,75.699,7.246
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6132,عبود في البيت,MOVIE,Two young boys must work together to stop robb...,2023,NaN,81,"family, comedy",['KW'],NaN,NaN,NaN,3.351,2.000
6133,Sweetie,MOVIE,"‘Theatre is my life,’ Yıldız Kenter admits in ...",2023,NaN,120,documentation,['TR'],NaN,7.9,209.0,2.450,7.200
6134,Sommore: Queen Chandelier,MOVIE,This Queen of Comedy shines as she takes the s...,2023,NaN,69,comedy,['US'],NaN,6.1,91.0,1.960,NaN
6135,All Na Vibes,MOVIE,The lives of three teenagers and a hit-man int...,2023,NaN,80,drama,['NG'],NaN,5.2,18.0,1.357,4.000
6136,Going to Heaven,MOVIE,"A story about young boy sultan, 11 years old l...",2023,NaN,90,family,['AE'],NaN,7.0,40.0,NaN,NaN

CONTENT QUESTIONS

Question 1: Are there more movies or tv shows in Netflix?

Findings: there are significantly more movies than tv shows in netflix.

Insight: Netflix has a larger inventory of movies likely because movies are faster and cheaper to produce, which allows the platform to quickly scale its content library.

Question 2: Are Netflix focussing more on movies or tv shows?

Findings: They are significantly focussing on more movies than tv shows.

Insight: Netflix are still largely focussing on movies because of the speed and shortness of the movies, and also the cheapness of producing movies compared to tv shows.

In [7]:
data.groupby("type").agg({"type":"count","imdb_score":"mean","imdb_votes":"mean"})

       type  imdb_score    imdb_votes
type
MOVIE  3831    6.266761  23624.303134
SHOW   2306    6.992067  17098.128791

In [8]:
data.groupby(["type","release_year"]).agg({"type":"count","imdb_score":"mean","imdb_votes":"mean"})

                    type  imdb_score    imdb_votes
type  release_year
MOVIE 1954             2    7.450000  23902.500000
      1956             1    6.700000    703.000000
      1958             1    7.500000   4878.000000
      1962             1    6.900000    312.000000
      1963             1    7.600000   2670.000000
...                  ...         ...           ...
SHOW  2019           315    7.089691  12028.941581
      2020           333    6.878339  10587.476534
      2021           326    6.815232   8844.966887
      2022           370    6.637037   6666.310541
      2023            50    6.642553   2924.127660

[101 rows x 3 columns]

TIME QUESTIONS

Question 1: Are Netflix's newer content more common?

Findings: Yes, their newer content are more common now.

Question 2: Have their content increased over time?

Findings: Yes, their content have increased over time.

Insight: Netflix has significantly ramped up content production in rescent years, suggesting an aggresive growth strategy to compete globally and retain subscribers. This is mostly due to their colaboration with movie production companies in deferent parts of the world to be able to supply the diverse demands of different people based on an accurate description of their societal and culture trends and also current trends in their local, to be able to supply contents that the audience can relate with.

In [9]:
data.groupby("release_year").agg({"release_year":"count","imdb_score":"mean","imdb_votes":"mean"}).tail(20)

              release_year  imdb_score     imdb_votes
release_year
2004                    35    6.800000   50920.548387
2005                    29    6.737037   87560.518519
2006                    39    7.000000   56009.810811
2007                    35    6.662857   27926.285714
2008                    43    6.934884  136700.674419
2009                    55    6.881132   64327.981132
2010                    53    6.815094   53114.301887
2011                    61    6.959322   52294.372881
2012                    84    6.992500   54933.937500
2013                   103    6.771134   75403.854167
2014                   137    6.819380   38899.759690
2015                   195    6.792553   32110.388298
2016                   312    6.746959   24392.266892
2017                   475    6.635841   17012.895787
2018                   743    6.562482   11027.111270
2019                   788    6.586761   12175.968927
2020                   829    6.364023   10752.235043
2021                   868    6.369154    9971.274093
2022                   915    6.271192    9585.520142
2023                    97    6.529213    3970.022472

Cleaning production_countries column for better analysis of countries movies come from.

In [10]:
data["production_countries"]=data["production_countries"].str.strip("[]")
data["production_countries"]=data["production_countries"].str.strip("'")
data

,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,51,documentation,US,1.0,NaN,NaN,0.601,NaN
1,Rocky,MOVIE,"When world heavyweight boxing champion, Apollo...",1976,PG,119,"drama, sport",US,NaN,8.1,588100.0,106.361,7.782
2,Grease,MOVIE,Australian good girl Sandy and greaser Danny f...,1978,PG,110,"romance, comedy",US,NaN,7.2,283316.0,33.160,7.406
3,The Sting,MOVIE,A novice con man teams up with an acknowledged...,1973,PG,129,"crime, drama, comedy, music",US,NaN,8.3,266738.0,24.616,8.020
4,Rocky II,MOVIE,After Rocky goes the distance with champ Apoll...,1979,PG,119,"drama, sport",US,NaN,7.3,216307.0,75.699,7.246
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6132,عبود في البيت,MOVIE,Two young boys must work together to stop robb...,2023,NaN,81,"family, comedy",KW,NaN,NaN,NaN,3.351,2.000
6133,Sweetie,MOVIE,"‘Theatre is my life,’ Yıldız Kenter admits in ...",2023,NaN,120,documentation,TR,NaN,7.9,209.0,2.450,7.200
6134,Sommore: Queen Chandelier,MOVIE,This Queen of Comedy shines as she takes the s...,2023,NaN,69,comedy,US,NaN,6.1,91.0,1.960,NaN
6135,All Na Vibes,MOVIE,The lives of three teenagers and a hit-man int...,2023,NaN,80,drama,NG,NaN,5.2,18.0,1.357,4.000
6136,Going to Heaven,MOVIE,"A story about young boy sultan, 11 years old l...",2023,NaN,90,family,AE,NaN,7.0,40.0,NaN,NaN

In [11]:
data

,title,type,description,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_score,imdb_votes,tmdb_popularity,tmdb_score
0,Five Came Back: The Reference Films,SHOW,This collection includes 12 World War II-era p...,1945,TV-MA,51,documentation,US,1.0,NaN,NaN,0.601,NaN
1,Rocky,MOVIE,"When world heavyweight boxing champion, Apollo...",1976,PG,119,"drama, sport",US,NaN,8.1,588100.0,106.361,7.782
2,Grease,MOVIE,Australian good girl Sandy and greaser Danny f...,1978,PG,110,"romance, comedy",US,NaN,7.2,283316.0,33.160,7.406
3,The Sting,MOVIE,A novice con man teams up with an acknowledged...,1973,PG,129,"crime, drama, comedy, music",US,NaN,8.3,266738.0,24.616,8.020
4,Rocky II,MOVIE,After Rocky goes the distance with champ Apoll...,1979,PG,119,"drama, sport",US,NaN,7.3,216307.0,75.699,7.246
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6132,عبود في البيت,MOVIE,Two young boys must work together to stop robb...,2023,NaN,81,"family, comedy",KW,NaN,NaN,NaN,3.351,2.000
6133,Sweetie,MOVIE,"‘Theatre is my life,’ Yıldız Kenter admits in ...",2023,NaN,120,documentation,TR,NaN,7.9,209.0,2.450,7.200
6134,Sommore: Queen Chandelier,MOVIE,This Queen of Comedy shines as she takes the s...,2023,NaN,69,comedy,US,NaN,6.1,91.0,1.960,NaN
6135,All Na Vibes,MOVIE,The lives of three teenagers and a hit-man int...,2023,NaN,80,drama,NG,NaN,5.2,18.0,1.357,4.000
6136,Going to Heaven,MOVIE,"A story about young boy sultan, 11 years old l...",2023,NaN,90,family,AE,NaN,7.0,40.0,NaN,NaN

GEOGRAPHY QUESTIONS

Question 1: Which countries produce the most contents on netflix?

Findings: United states produced the most movies on netflix.

Insight: Netflix heavily relies on the United States of America's produced content, indicating a centralised production strategy that may limit regional diversity. This heavy relying on USA content may be as a result of the global demand for production contents from the USA and the high quality of production which the country have kept for many decades which might have been made the global standards for movie pproduction.

Question 2: Is Netflix dominated by certain areas?

Findings: United states vastly dominates netflix, followed by Asian countries like India and Japan.

Insight: The rise of Asian content (India, Japan, Korea) suggests that Netflix is expanding into international markets and adapting into regional audiences. this might be as a result of the increased demand for contents from these countries for their high quality content production and storytelling which have caught global attention.

In [12]:
data["production_countries"]=data["production_countries"].replace("'","")
datad = data.groupby("production_countries").agg({"production_countries":"count","imdb_score":"mean","imdb_votes":"mean"})
datad

                      production_countries  imdb_score    imdb_votes
production_countries
                                       176    6.196947    659.062016
AE                                      14    5.161538    509.923077
AE', 'EG', 'RO', 'SA                     1    2.300000    242.000000
AE', 'LB                                 1    6.400000     64.000000
AE', 'US                                 1    6.300000   5089.000000
...                                    ...         ...           ...
ZA', 'IE                                 1    7.200000  41265.000000
ZA', 'RW', 'GB                           1    6.500000   1494.000000
ZA', 'US                                 1    5.400000    241.000000
ZA', 'US', 'DE                           1    6.800000   2979.000000
ZW                                       1    6.000000    378.000000

[438 rows x 3 columns]

In [13]:
datad = datad.rename(columns={"production_countries":"count"})
datad = datad.sort_values(by="count",ascending=False)
datad

                      count  imdb_score    imdb_votes
production_countries
US                     1981    6.600754  36207.051324
IN                      633    6.439094  11730.523490
JP                      278    7.042857  10805.455598
KR                      259    7.285903   6823.629956
GB                      235    7.002667  26329.160714
...                     ...         ...           ...
FR', 'QA', 'MA            1    6.500000   1324.000000
FR', 'QA                  1    7.400000  10134.000000
FR', 'LU', 'US            1    6.900000   3855.000000
FR', 'LB', 'PS            1    8.100000     39.000000
ZW                        1    6.000000    378.000000

[438 rows x 3 columns]

CATEGORY QUESTIONS

Question 1: What genre appears most?

Findings: The comedy genre is the most genre on netflix.

Insight: Comedy dominates Netflix's catalog likely because it has broad global appeal and lower cultural barriers compared to niche genres.

Question 2: Are certain genre growing?

Findings: Yes, action and action/animation are growing.

Insight: The rapid growth of action and animation indicates shifting in audience preferences towards high-engagement, visually driven content. the rapid growth of action and animation content on netflix might be as a result of younger generations who grew up consuming action and animated content, and continued to consume the same content as adults. this suggests a growing demand for animation and acyion contents, making it a strategic area for netflix to invest in to attract or retain younger audiences.
One potential risk is that high-quality production is concentrated in a few regions. this may reduce the ability of netflix to scale these contents globally, potentially creating supply constraints if demand continues to grow rapidly.

In [14]:
data.groupby("genres").agg({"genres":"count","imdb_score":"mean","imdb_votes":"mean"})
datam = data.groupby("genres").agg({"genres":"count","imdb_score":"mean","imdb_votes":"mean"})
datam

                                         genres  imdb_score    imdb_votes
genres
                                             57    7.600000   2069.000000
action                                       14    5.370000  25253.111111
action, animation                             5    6.766667   1476.333333
action, animation, comedy                     1    4.400000    995.000000
action, animation, comedy, crime, drama       1    7.900000   5679.000000
...                                         ...         ...           ...
western, drama, action, crime                 1    8.300000  36835.000000
western, drama, history                       1    6.600000    870.000000
western, horror, action                       1    6.000000   2740.000000
western, music, fantasy                       1    4.000000    741.000000
western, thriller, action, romance            1    6.500000  97101.000000

[1712 rows x 3 columns]

In [15]:
datam = datam.rename(columns={"genres":"count"})
datam = datam.sort_values(by="count",ascending=False)
datam

,count,imdb_score,imdb_votes
genres,,,
comedy,516,6.310217,9274.305011
drama,362,6.631186,7695.996599
documentation,348,7.135943,3020.380435
"drama, romance",163,6.551235,13100.518519
reality,152,6.268345,1553.546763
...,...,...,...
"crime, documentation, european",1,6.900000,25238.000000
"crime, documentation, drama, fantasy",1,7.000000,4427.000000
"crime, comedy, western",1,5.700000,9754.000000
"crime, comedy, war, action, drama, history, thriller",1,5.400000,1993.000000
"western, thriller, action, romance",1,6.500000,97101.000000

In [16]:
datat = data.groupby(["genres","release_year"]).agg({"genres":"count"}).head(20)
# datat = datat.sort_values(by="genres",ascending=False)
datat

                     genres
genres release_year
       1998               1
       2003               1
       2006               1
       2012               1
       2013               1
       2014               3
       2016               1
       2017               4
       2018               8
       2019               4
       2020              13
       2021              15
       2022               4
action 2015               1
       2016               1
       2017               2
       2018               1
       2019               1
       2020               2
       2021               3

In [17]:
datag = data.groupby("release_year").agg({"title":"count","imdb_score":"mean","imdb_votes":"mean"}).tail(20)
datag = datag.sort_values(by="title",ascending=False)
datag

              title  imdb_score     imdb_votes
release_year
2022            915    6.271192    9585.520142
2021            868    6.369154    9971.274093
2020            829    6.364023   10752.235043
2019            788    6.586761   12175.968927
2018            743    6.562482   11027.111270
2017            475    6.635841   17012.895787
2016            312    6.746959   24392.266892
2015            195    6.792553   32110.388298
2014            137    6.819380   38899.759690
2013            103    6.771134   75403.854167
2023             97    6.529213    3970.022472
2012             84    6.992500   54933.937500
2011             61    6.959322   52294.372881
2009             55    6.881132   64327.981132
2010             53    6.815094   53114.301887
2008             43    6.934884  136700.674419
2006             39    7.000000   56009.810811
2007             35    6.662857   27926.285714
2004             35    6.800000   50920.548387
2005             29    6.737037   87560.518519

CORE INSIGHT

Netflix's growth strategy appears to rely on rapidely expanding it's content library, primarily through movies, while increasingly investing in tv shows to improve long-term user engagement. although the platform is still dominated by content fron the USA, the continual rise of asian content production signals a shift towards global market expansion. at the same time, the growth of action and animation genres suggests and evolving audience preference towards more dynamic and engaging content.

RECOMENDATIONS

Based on the analysis from the data, Netflix should expand partnerships with international and local production houses to diversify its content library and better engage its regional audiences. This will help attract new users in underepresented markets while reducing reliance on content from the USA. 
Additionally, Netflix should increase investments in fast growing genres such as action and animation to align with evolving audience preferences to maximize engagement.